version: 2.0.0
title: Fred Condo’s Github
description: Building better websites since 1994
logo: assets/fred.svg
google_analytics: 
show_downloads: false
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
